export const CATEGORIES = {
  FULL_TIME_MEMBERS: 'Full-time Members',
  BOARD_OF_DIRECTORS: 'Board of Directors',
  ADVISORS: 'Advisors',
};

export const MEMBERS = [
  {
    name: 'Mrinal Wadwha',
    position: 'CTO',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'US',
    photo: 'mrinal-wadwha.png',
    description: 'Loves rock-n-roll and has a dog named Sargent Pepper',
  },
  {
    name: 'Matthew Gregory',
    position: 'CEO',
    categories: [CATEGORIES.FULL_TIME_MEMBERS, CATEGORIES.BOARD_OF_DIRECTORS],
    country: 'US',
    photo: 'matthew-gregory.png',
    description: 'Started his career in professional sailing and has a passion for meteorology',
  },
  {
    name: 'Sabeen Syed',
    position: 'VP of Engineering',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'US',
    photo: 'sabeen-syed.png',
    description:
      'Enjoys reading historical fiction, playing board games and running after her 4 kids',
  },
  {
    name: 'Antoine van Gelder',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'ZA',
    photo: 'antoine-van-gelder.png',
    description: 'Raised two kids and still loves playing guitar',
  },
  {
    name: 'Daniil Fedotov',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'CA',
    photo: 'daniil-fedotov.png',
    description: 'lorem',
  },
  {
    name: 'Michael Uti',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'NG',
    photo: 'michael-uti.png',
    description: 'lorem',
  },
  {
    name: 'Oleksandr Deundiak',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'UA',
    photo: 'oleksandr-deundiak.png',
    description: 'Rides really fast motorcycles',
  },
  {
    name: 'Piotr Sobieszczański',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'PL',
    photo: 'piotr-sobieszczanski.png',
    description: 'Loves nature and passion about space exploration',
  },
  {
    name: 'Pablo Polvorin',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'AR',
    photo: 'pablo-polvorin.png',
    description:
      'Once debugged a performance issue on a large scale system below a giant tree in the amazon',
  },

  {
    name: 'Adrian Benavides',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'ES',
    photo: 'adrian-benavides.png',
    description: 'lorem',
  },
  {
    name: 'Katharina Fey',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'DE',
    photo: 'katharina-fey.png',
    description: 'lorem',
  },
  {
    name: 'Toralf Wittner',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'DE',
    photo: 'toralf-wittner.png',
    description: 'lorem',
  },
  {
    name: 'Thom Chiovoloni',
    position: 'Engineer',
    categories: [CATEGORIES.FULL_TIME_MEMBERS],
    country: 'US',
    photo: 'thom-chiovoloni.png',
    description: 'Hobbyist game designer and pixel artist',
  },
  {
    name: 'Maryanna Saenko',
    position: 'Board Member',
    categories: [CATEGORIES.BOARD_OF_DIRECTORS],
    country: 'US',
    photo: 'maryanna-saenko.png',
    description: 'Partner at Future Ventures',
  },
  {
    name: 'Arra Malekzadeh',
    position: 'Board Member',
    categories: [CATEGORIES.BOARD_OF_DIRECTORS],
    country: 'US',
    photo: 'arra-malekzadeh.png',
    description: 'Partner at Craft Ventures',
  },
  {
    name: 'Fergal Donoher',
    position: 'Board Member',
    categories: [CATEGORIES.BOARD_OF_DIRECTORS],
    country: 'US',
    photo: 'fergal-donoher.png',
    description: 'SVP at Flex',
  },
  {
    name: 'Patricia Muoio',
    position: 'Board Member',
    categories: [CATEGORIES.BOARD_OF_DIRECTORS],
    country: 'US',
    photo: 'patricia-muoio.png',
    description: 'Partner at SineWave Ventures',
  },
  {
    name: 'Joanna Drake',
    position: 'Board Member',
    categories: [CATEGORIES.BOARD_OF_DIRECTORS],
    country: 'US',
    photo: 'joanna-drake.png',
    description: 'Partner at Core Ventures',
  },
  {
    name: 'Jeanne DeWitt Grosser',
    position: 'Product Advisor',
    categories: [CATEGORIES.ADVISORS],
    country: 'US',
    photo: 'j-dewitt-grosser.png',
    description: 'Head of Revenue & Growth at Stripe',
  },
  {
    name: 'Matthew Trifiro',
    position: 'Product Advisor',
    categories: [CATEGORIES.ADVISORS],
    country: 'US',
    photo: 'matthew-trifiro.png',
    description: 'CMO at Vapor.io',
  },
  {
    name: 'Brian Mullen',
    position: 'Product Advisor',
    categories: [CATEGORIES.ADVISORS],
    country: 'US',
    photo: 'brian-mullen.png',
    description: 'CMO at InfluxData',
  },
];
