export const CATEGORIES = {
  BOARD_MEMBERS: 'Board Members',
  ADVISORS: 'Advisors',
  EMPLOYEE_ROSTER: 'Employee Roster',
};

export const MEMBERS = [
  {
    name: 'Mrinal Wadwha',
    position: 'CTO',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'US',
    photo: 'mrinal-wadwha.png',
    description: 'lorem',
  },
  {
    name: 'Matthew Gregory',
    position: 'CEO/ Board Member',
    categories: [CATEGORIES.EMPLOYEE_ROSTER, CATEGORIES.BOARD_MEMBERS],
    country: 'US',
    photo: 'matthew-gregory.png',
    description: 'lorem',
  },
  {
    name: 'Sabeen Syed',
    position: 'VP Engineering',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'US',
    photo: 'sabeen-syed.png',
    description: 'lorem',
  },
  {
    name: 'Antoine van Gelder',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'ZA',
    photo: 'antoine-van-gelder.png',
    description: 'lorem',
  },
  {
    name: 'Daniil Fedotov',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'CA',
    photo: 'daniil-fedotov.png',
    description: 'lorem',
  },
  {
    name: 'Michael Uti',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'NG',
    photo: 'michael-uti.png',
    description: 'lorem',
  },
  {
    name: 'Oleksandr Deundiak',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'UA',
    photo: 'oleksandr-deundiak.png',
    description: 'lorem',
  },
  {
    name: 'Piotr Sobieszczański',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'PL',
    photo: 'piotr-sobieszczanski.png',
    description: 'lorem',
  },
  {
    name: 'Thom Chiovoloni',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'US',
    photo: 'thom-chiovoloni.png',
    description: 'lorem',
  },
  {
    name: 'Toralf Wittner',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'DE',
    photo: 'toralf-wittner.png',
    description: 'lorem',
  },
  {
    name: 'Katharina Fey',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'DE',
    photo: 'katharina-fey.png',
    description: 'lorem',
  },
  {
    name: 'Adrian Benavides',
    position: 'Engineer',
    categories: [CATEGORIES.EMPLOYEE_ROSTER],
    country: 'ES',
    photo: 'adrian-benavides.png',
    description: 'lorem',
  },
  {
    name: 'Maryanna Saenko',
    position: 'Borad Member/ Partner @ Future Ventures',
    categories: [CATEGORIES.BOARD_MEMBERS],
    country: 'US',
    photo: 'maryanna-saenko.png',
    description: 'lorem',
  },
  {
    name: 'Arra Malekzadeh',
    position: 'Board Observer/ Partner @ Craft Ventures',
    categories: [CATEGORIES.BOARD_MEMBERS],
    country: 'US',
    photo: 'arra-malekzadeh.png',
    description: 'lorem',
  },
  {
    name: 'Fergal Donoher',
    position: 'Board Advisor  SVP @ Flex',
    categories: [CATEGORIES.BOARD_MEMBERS],
    country: 'US',
    photo: 'fergal-donoher.png',
    description: 'lorem',
  },
  {
    name: 'Patricia Muoio',
    position: 'Borad Member/ Partner @ SineWave Ventures',
    categories: [CATEGORIES.BOARD_MEMBERS],
    country: 'US',
    photo: 'patricia-muoio.png',
    description: 'lorem',
  },
  {
    name: 'Joanna Drake Earl',
    position: 'Board Observer/ Partner @ Core Ventures',
    categories: [CATEGORIES.BOARD_MEMBERS],
    country: 'US',
    photo: 'joanna-drake-earl.png',
    description: 'lorem',
  },
  {
    name: 'J. DeWitt Grosser',
    position: 'Head of Americas Revenue & Growth at Stripe',
    categories: [CATEGORIES.ADVISORS],
    country: 'US',
    photo: 'j-dewitt-grosser.png',
    description: 'lorem',
  },
  {
    name: 'Matthew Trifiro',
    position: 'CMO at Vapor',
    categories: [CATEGORIES.ADVISORS],
    country: 'US',
    photo: 'matthew-trifiro.png',
    description: 'lorem',
  },
  {
    name: 'Brian Mullen',
    position: 'CMO at InfluxData',
    categories: [CATEGORIES.ADVISORS],
    country: 'US',
    photo: 'brian-mullen.png',
    description: 'lorem',
  },
];
