import { isString } from 'lodash';

import colors from '@theme/colors';
import { ITeamMember } from '@typings/TeamMember';

import getRandomFromArray from './getRandomFromArray';

const AUTOGENERATED_BG_COLORS = [
  colors.extras.iceCold,
  colors.extras.pictonBlue,
]

const enhanceTeamMembers = (teamMembers: ITeamMember[]): ITeamMember[] => teamMembers.map(member => ({
    ...member,
    bgColor: (member.bgColor && isString(member.bgColor)) ? member.bgColor : getRandomFromArray<string>(AUTOGENERATED_BG_COLORS)
  }))

export default enhanceTeamMembers;
